blueprints/characters.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from replit import db, database
from flask_login import current_user

charactersBP = Blueprint('charactersBP', __name__, url_prefix='/characters')

from .pull import getOwnedChars,getPulledChars

@charactersBP.route('/<chr_ind>', methods=['GET','POST'])
def character_page(chr_ind):

  if request.method == 'POST':
    #button = request.form.get('submit_button')
    
    if chr_ind in db['players'][current_user.id]['wishlist']:
      db['players'][current_user.id]['wishlist'].remove(chr_ind)
      flash('Removed character from wishlist.', category='success')
    else:
      db['players'][current_user.id]['wishlist'].append(chr_ind)
      flash('Added character to wishlist.', category='success')
  
  #Determines if a characer is owned
  owned = getOwnedChars()
  if chr_ind in owned:
    owner = owned[chr_ind]
  else:
    owner = None
  pulled = getPulledChars()
  if chr_ind in pulled:
    puller = pulled[chr_ind]
  else:
    puller = None

  character = database.to_primitive(db['characters'][chr_ind])
  rarity = db['rarity_names'][str(character['rarity'])]
  rarity += " " + "☆"*character['rarity']
  
  in_wishlist = chr_ind in db['players'][current_user.id]['wishlist']
  players_wished = [pname for pname,player in db['players'].items() if chr_ind in player['wishlist']]

  return render_template('characters/character_page.html', user = current_user, character = character, chr_ind = chr_ind, owner=owner, puller=puller, rarity = rarity, in_wishlist=in_wishlist, players_wished=players_wished)

@charactersBP.route('/')
def characters():
  if current_user.is_authenticated:
    char_list = [(url_for('charactersBP.character_page', chr_ind = i), i, char) for i,char in sorted(db['characters'].items(), key=lambda x:int(x[0]))]
    
    return render_template('characters/characters.html', user = current_user, char_list = char_list)
  else:
    return redirect(url_for('otherBP.home'))

@charactersBP.route('/proposal', methods=['GET','POST'])
def proposal():
  if request.method == 'POST':
    button = request.form.get('submit_button')

    if button == 'propose':
      #Gets all the information from the form
      name = request.form.get('char_name')
      series = request.form.get('char_series')

      print(f'name:   {len(name)}')
      print(f'series: {len(series)}')
    
      #Checks the information to ensure that it is valid
      if  len(name) == 0 or len(series) == 0 :
          flash('Please type a name and a series.', category='error')
      else:
      
        new_char = {
          'image': None,
          'name': name,
          'status': 'pending',
          'series': series,
          'suggested_by': None,
          'suggested_timestamp': 'now, duh',
          'approval_votes': {},
          'rarity_votes': {}
        }

        db['proposed_characters'].append(new_char)
        flash('Character proposed!', category='success')
    
    elif button == 'vote':
      #print(request.form)
      for k,v in request.form.items():
        if k.split('-')[0] in ['charRarity', 'charApprove']:
          if k.split('-')[0] == 'charRarity':
            voteType = 'rarity_votes'
          else:
            voteType = 'approval_votes'
          char_ind = int(k.split('-')[1])
          option = v.split('-')[1]
          db['proposed_characters'][char_ind][voteType][current_user.id] = option


      flash('Voted')

  proposed_characters = [(str(i), c) for i,c in enumerate(db['proposed_characters']) if c['status']=='pending']

  return render_template('characters/proposal.html', user = current_user, proposed_characters = proposed_characters)

blueprints/images.py
from PIL import Image, ImageFont, ImageDraw 
import requests
from io import BytesIO

from flask import Blueprint, render_template, send_file
from flask_login import current_user
from replit import db

imagesBP = Blueprint('imagesBP', __name__)

#Converts a PIL image object to something that Flask can serve.
def serve_pil_image(pil_img):
    img_io = BytesIO()
    pil_img.save(img_io, 'PNG', quality=70)
    img_io.seek(0)
    return send_file(img_io, mimetype='image/png')

#Generates artwork for a charater with titles and borders
@imagesBP.route('/art/<arttype>/<charID>-<artID>.png')
def characterArt(arttype, charID, artID):

  if arttype == 'regular':
    size = (1106, 1482)
  elif arttype == 'mini':
    size = (665, 691)
  else:
    return

  #Gets all the necessary data
  character = db['characters'][charID]
  name = character['name']
  rarity = character['rarity']
  art = character['images'][int(artID)]
  url = art['url']
  crop = art['portrait']
  nsfw = art['NSFW']
  
  #Determines if NSFW art can be displayed
  if current_user.is_authenticated:
    allow_nsfw = db['players'][current_user.id]['NSFW_shown']
  else:
    allow_nsfw = False

  #Gets all of the images that it's going to work with
  img = Image.new('RGB', size)

  if nsfw and not allow_nsfw:
    artwork = Image.new('RGB', size)
    crop = None
  else:
    artwork = Image.open(requests.get(url, stream=True).raw)
    
  border = Image.open(f"images/{arttype}_frames/rarity{rarity}.png")

  #If it's a mini art, crop the image
  if arttype == 'mini' and crop is not None:
    artwork = artwork.crop(tuple(crop))

  #Scale the artwork to the correct size and combine the artwork and the frame
  artwork = artwork.resize(size)
  img.paste(artwork, (0,0))
  img.paste(border, (0,0), mask=border)
  
  #If it's a regular art, add the name of the character
  if arttype == 'regular':
    text_size = 100
    title_font = ImageFont.truetype('fonts/broadway.ttf', text_size)
    
    while(title_font.getsize(name)[0] > 530):
      text_size -= 5
      title_font = ImageFont.truetype('fonts/broadway.ttf', text_size)

    title_text = name
    draw = ImageDraw.Draw(img)
    draw.text((450,1370+(95-title_font.getsize(name)[1])/2), title_text, (0, 0, 0), font=title_font)

  if arttype == 'mini':
    img = img.resize((100,100))

  return serve_pil_image(img)

blueprints/players.py
import datetime
import time

import pytz

from flask import Blueprint, render_template, redirect, url_for, request, flash
from replit import db, database
from flask_login import current_user

playersBP = Blueprint('playersBP', __name__, url_prefix='/players')

from .pull import pullChar
est = pytz.timezone('US/Eastern')

#A player's main page
@playersBP.route('/<ply_ind>', methods=['GET','POST'])
def player_page(ply_ind):

  if request.method == 'POST':
    button = request.form.get('submit_button')

    #If a user is checking in to claim their coins
    if button == 'check-in':
      last_check_in = db['players'][current_user.id]['last_check_in']
      now = int(time.time())

      #Get's the previous check in time and the current time
      prev = datetime.datetime.utcfromtimestamp(last_check_in)
      prev = est.localize(prev)
      curr = datetime.datetime.utcfromtimestamp(now)
      curr = est.localize(curr)

      #Calculates the number of days since the last check in
      diff = (curr.date()-prev.date()).days

      #Adds the appropriate number of coins
      db['players'][current_user.id]['last_check_in'] = now
      db['players'][current_user.id]['coins'] += diff

      #Flashes success message to user
      flash(f'You have redeemed {diff} Koins.', category='success')
    
    #If a user is changing their NSFW status
    elif button.split('-')[0] == 'NSFW':
      toggle = button.split('-')[1] == 'on'
      db['players'][current_user.id]['NSFW_shown'] = toggle
      flash('Preferences updated. Please clear cache.', category='success')

    elif button == 'expand-roster':
      player = db['players'][ply_ind]
      roster_size = player['max_roster']

      if roster_size >= len(db['expansion_costs']):
        flash("You already have the max roster size.", category='error')
      else:
        cost = db['expansion_costs'][roster_size]
        
        if cost > player['coins']:
          flash("You don't have enough coins.", category='error')
        else:
          #Deducting the cost of the banner and adding to their roster
          db['players'][current_user.id]['max_roster'] += 1
          db['players'][current_user.id]['coins'] -= cost
          
          #Returns a page to show the user thier pull
          return pullChar(banner_name='base')

  if current_user.is_authenticated:

    player = db['players'][ply_ind]

    #Get a list of owned characters and wishlisted characters by the player
    owned_characters = [(char_id, db['characters'][char_id]) for char_id in player['roster']]
    wishlist_characters = [(char_id, db['characters'][char_id]) for char_id in player['wishlist']]

    #Gets the time that the player last checked in
    last_check_in = player['last_check_in']
    check_in = datetime.datetime.utcfromtimestamp(last_check_in)
    check_in = est.localize(check_in)
    check_in_string = check_in.strftime("%a, %b %d, %Y %I:%M %Z%z")

    #Returns the HTML template
    return render_template('players/player_page.html', user = current_user, player = (ply_ind, database.to_primitive(db['players'][ply_ind])), owned_characters = owned_characters, wishlist_characters=wishlist_characters, check_in = check_in_string)
  
  #If the user is not logged in, redirect to the home page.
  else:
    return redirect(url_for('otherBP.home'))

#Page to display all the players
@playersBP.route('/')
def players():
  if current_user.is_authenticated:
    #Gets a list of players to pass to the HTML template.
    player_names = db['players'].keys()
    return render_template('players/players.html', user = current_user, player_names = player_names)
  #If the user is not logged in, redirect to the home page.
  else:
    return redirect(url_for('otherBP.home'))

templates/characters/character_page.html
{% extends "base.html" %} {% block title %}{{ character['name'] }}{% endblock %} {% block content %}
<h2>{{ chr_ind }}. {{ character['name'] }} <i>({{ character['series'] }})</i></h2>
<h3>{{ rarity }}</h3>

{% if character['description'] is not none %}
  {{character['description']}}<br>
{% endif%}

{% if owner is not none %}
  Owned by <a href="{{ url_for('playersBP.player_page', ply_ind = owner) }}"> {{owner}}</a><br>
{% endif %}
{% if puller is not none %}
  Pulled by <a href="{{ url_for('playersBP.player_page', ply_ind = puller) }}"> {{puller}}</a><br>
{% endif %}

<img src="{{url_for('imagesBP.characterArt', arttype='regular', charID=chr_ind, artID=0)}}" height="500"></img>

<h3>Wishlists</h3>
{% for player in players_wished %}
  <a href="{{ url_for('playersBP.player_page', ply_ind = player) }}"> {{ player }}</a><br>
{% endfor %}

<form method="POST">
  <button type="submit" class="btn btn-primary" name="submit_button" value="toggle-wishlist">{{'Remove from ' if in_wishlist else 'Add to '}}Wishlist</button>
</form>

{% endblock %}

templates/characters/characters.html
{% extends "base.html" %} {% block title %}Characters{% endblock %} {% block content %}
{% for url, i, c in char_list %}
  <a href="{{ url }}">
    <img
      src="{{url_for('imagesBP.characterArt', arttype='mini', charID=i, artID=0)}}"
      height="100"
      alt="{{c['name']}}"
      title="{{c['name']}}"
    ></img>
  </a>
{% endfor %}
{% endblock %}

templates/characters/charactersOLD.html
{% extends "base.html" %} {% block title %}Characters{% endblock %} {% block content %}
{% for url, i, c in char_list %}
  <a href="{{ url }}"><img src="{{url_for('imagesBP.characterArt', arttype='mini', charID=i, artID=0)}}" height="100"></img>{{ i }}. {{ c['name'] }} ({{ c['series']}})</a><br>
{% endfor %}
{% endblock %}

templates/characters/proposal.html
{% extends "base.html" %} {% block title %}Character Proposals{% endblock %} {% block content %}
<form method="POST">
  <h3 align="center">Character Proposal</h3>
  <div class="form-group">
    <label for="username">Character Name</label>
    <input
      type="text"
      class="form-control"
      id="char_name"
      name="char_name"
      placeholder="Enter character name"
    />
  </div>
  <div class="form-group">
    <label for="password">Character Series</label>
    <input
      type="text"
      class="form-control"
      id="char_series"
      name="char_series"
      placeholder="Enter character series"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary" name="submit_button" value="propose">Propose</button>
</form>

<form method="POST">
  <h2 align="center">Pending characters</h2>

{% for i, character in proposed_characters %}
<h3>{{ character['name']}} ({{ character['series'] }})</h3>
<u>Approve</u>
  {% for j in ['Yes', 'No', 'Abstain'] %}
    <div class="form-check">
      <input 
        class="form-check-input"
        type="radio"
        name="{{ 'charApprove-' + i }}"
        value="{{ 'option-' + j}}" 
        {{ 'checked' if character['approval_votes'][user.id] == j else '' }}
      ><label class="form-check-label" for="{{ 'charApprove-' + i }}">{{j}}</label>
    </div>
  {% endfor %}
<br>
<u>Rarity</u>
  {% for j in ['1','2','3','4','5', 'Abstain'] %}
    <div class="form-check">
      <input 
        class="form-check-input"
        type="radio"
        name="{{ 'charRarity-' + i }}"
        value="{{ 'option-' + j}}" 
        {{ 'checked' if character['rarity_votes'][user.id] == j else '' }}
      ><label class="form-check-label" for="{{ 'charRarity-' + i }}">{{j}}</label>
    </div>
  {% endfor %}
<br>
{% endfor %}

  <button type="submit" class="btn btn-primary" name="submit_button" value="vote">Save</button>
</form>





{% endblock %}